# configure updates globally
# default: all
# allowed: all, insecure, False
update: all

# configure dependency pinning globally
# default: True
# allowed: True, False
pin: True

# Specify requirement files by hand, pyup seems to struggle to
# find the ones in the app_name folder
requirements:
  - "requirements.txt"
  - "{{cookiecutter.repo_name}}/requirements/base.txt"
  - "{{cookiecutter.repo_name}}/requirements/local.txt"
  - "{{cookiecutter.repo_name}}/requirements/production.txt"
